server:
  port: 9090
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/ocat?useSSL=false&autoReconnect=true
    username: liuhaichuan
    password: Yjsd323IOm
logging:
  path: /app/logs
  level:
    com:
      lhc:
        ocat: DEBUG
com:
  lhc:
    ocat:
      mobileplatform:
        max-diff-count: 3 # 最大差量比较的版本个数（新版本包与之前多个旧版本包差量比较）
        workshop-path: /app/workshop # 差量比较工作目录
        online-url: http://49.233.169.151:8080
        package-download-path: /app/html/download/packages # 可以放到云上
        online-version-path: /app/html/online
        prep-online-version-path: /app/html/preview